#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A main.celery inspect ping
}

until worker_ready; do
  >&2 echo 'No celery workers available'
  sleep 1
done
>&2 echo 'Celery worker is available'

celery flower \
    --app=main.celery \
    --broker="redis://redis:6379/0"
